# Generated by Django 3.1.6 on 2022-01-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(choices=[('Bihar', 'Bihar'), ('Delhi', 'Delhi'), ('Kolkata', 'Kolkata'), ('Punjab', 'Punjab')], default=None, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', '1'), ('Female', '0')], default='Male', max_length=10)),
                ('dob', models.DateTimeField()),
                ('category', models.CharField(choices=[('Event', 'Event'), ('Fashion', 'Fashion'), ('Sports', 'Sports'), ('Food', 'Food'), ('Art and Portrait', 'Art and Portrait'), ('Architecture', 'Architecture'), ('Documentary', 'Documentary'), ('Travel', 'Travel'), ('Modelling and Lifestyle', 'Modelling and Lifestyle'), ('Nature and Wildlife', 'Natue and Wildlife'), ('Product', 'Product'), ('Photo Journalism', 'Photo journalism')], max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('status', models.BooleanField(choices=[('Available', True), ('Busy', False)], default=True)),
            ],
        ),
    ]
