# Generated by Django 3.1.6 on 2022-01-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy')], default='Available', max_length=20),
        ),
    ]
