# Generated by Django 4.0.1 on 2022-01-28 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0002_omniuser_customer_customer_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OmniUser',
        ),
    ]
