# Generated by Django 4.0.1 on 2022-01-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0005_alter_customer_area_alter_customer_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='photographer',
            old_name='name',
            new_name='fname',
        ),
        migrations.RemoveField(
            model_name='photographer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='photographer',
            name='dob',
        ),
        migrations.AddField(
            model_name='customer',
            name='lname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='photographer',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='photographer',
            name='area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='photographer',
            name='lname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
