# Generated by Django 3.1.6 on 2022-01-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0007_auto_20220130_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='photographer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
