# Generated by Django 4.0.1 on 2022-01-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0008_auto_20220130_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/profile'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img/profile'),
        ),
    ]
