# Generated by Django 4.0.1 on 2022-01-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0010_alter_photographer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img/profile'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img/profile'),
        ),
    ]
