# Generated by Django 4.0.1 on 2022-02-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0012_alter_customer_image_alter_photographer_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='payment_status',
            new_name='appointment_status',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Photographer',
            new_name='photographer',
        ),
        migrations.AddField(
            model_name='appointment',
            name='area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='zip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
