# Generated by Django 4.0.1 on 2022-02-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0014_alter_appointment_id_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='category',
            field=models.CharField(blank=True, choices=[('Event', 'Event'), ('Fashion', 'Fashion'), ('Sports', 'Sports'), ('Food', 'Food'), ('Art_and_Portrait', 'Art_and_Portrait'), ('Architecture', 'Architecture'), ('Documentary', 'Documentary'), ('Travel', 'Travel'), ('Modelling_and_Lifestyle', 'Modelling_and_Lifestyle'), ('Nature_and_Wildlife', 'Natue_and_Wildlife'), ('Product', 'Product'), ('Photo_Journalism', 'Photo_journalism')], max_length=100, null=True),
        ),
    ]
