# Generated by Django 3.1.6 on 2022-02-05 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0015_alter_photographer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel1', models.ImageField(upload_to='images/')),
                ('carousel2', models.ImageField(upload_to='images/')),
                ('carousel3', models.ImageField(upload_to='images/')),
                ('img1', models.ImageField(upload_to='images/')),
                ('img2', models.ImageField(upload_to='images/')),
                ('img3', models.ImageField(upload_to='images/')),
                ('img4', models.ImageField(upload_to='images/')),
                ('img5', models.ImageField(upload_to='images/')),
                ('head1', models.CharField(max_length=50)),
                ('head2', models.CharField(max_length=50)),
                ('head3', models.CharField(max_length=50)),
                ('head4', models.CharField(max_length=50)),
                ('head5', models.CharField(max_length=50)),
                ('date1', models.DateField()),
                ('date2', models.DateField()),
                ('date3', models.DateField()),
                ('date4', models.DateField()),
                ('date5', models.DateField()),
                ('desc1', models.CharField(max_length=400)),
                ('desc2', models.CharField(max_length=400)),
                ('desc3', models.CharField(max_length=400)),
                ('desc4', models.CharField(max_length=400)),
                ('desc5', models.CharField(max_length=400)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hub.photographer')),
            ],
        ),
    ]
