# Generated by Django 3.1.6 on 2022-02-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0016_auto_20220205_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='date3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='date4',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='date5',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='desc2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='desc3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='desc4',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='desc5',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='head2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='head3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='head4',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='head5',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='img5',
        ),
    ]
