# Generated by Django 3.1.6 on 2022-02-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0017_auto_20220205_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date1',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='desc1',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='head1',
            new_name='head',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='img1',
            new_name='img',
        ),
    ]
