# Generated by Django 4.0.1 on 2022-02-07 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0021_alter_appointment_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='carousel1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='carousel2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='carousel3',
        ),
    ]
