# Generated by Django 3.1.6 on 2022-02-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0025_auto_20220211_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
