# Generated by Django 3.1.6 on 2022-02-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0030_auto_20220212_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='no_of_feedback',
            field=models.IntegerField(default=0),
        ),
    ]
